export const data = [
  {
    id: 1,
    category: "Spices",
    title: " Ginger",
    price: 12.99,
    description: "Fresh and aromatic ginger for all your cooking needs.",
    rating: 4.5,
    imageUrl: "https://i.ibb.co/0jcPCQv/ada1.jpg",
  },
  {
    id: 2,
    category: "Spices",
    title: " Ginger",
    price: 11.99,
    description: "High-quality ginger, perfect for spice blends and teas.",
    rating: 4.2,
    imageUrl: "https://i.ibb.co/t2tznfL/ada2.jpg",
  },
  {
    id: 3,
    category: "Spices",
    title: " Ginger",
    price: 12.5,
    description: "Rich ginger flavor for a variety of dishes.",
    rating: 4.4,
    imageUrl: "https://i.ibb.co/fkBDK5s/ada3.png",
  },
  {
    id: 4,
    category: "Spices",
    title: " Ginger",
    price: 13.25,
    description: "Organically grown ginger with a fresh, zesty flavor.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/fY107d6/ada4.png",
  },
  {
    id: 5,
    category: "Spices",
    title: " Ginger",
    price: 11.75,
    description: "Fresh ginger, perfect for making ginger tea or spice blends.",
    rating: 4.5,
    imageUrl: "https://i.ibb.co/HTwrfmC/ada5.png",
  },
  {
    id: 6,
    category: "Spices",
    title: " Ginger",
    price: 12.99,
    description: "High-quality ginger for flavorful and aromatic cooking.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/CWnXJXQ/ada6.png",
  },
  {
    id: 7,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 15.99,
    description: "Organic cinnamon sticks for enhancing flavor.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/Pjt8yzy/darchini.jpg",
  },
  {
    id: 8,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 16.99,
    description: "Pure cinnamon powder for both sweet and savory dishes.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/fXQYXtR/darchini2.jpg",
  },
  {
    id: 9,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 15.75,
    description: "Fresh cinnamon with a rich and aromatic flavor.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/0JW1BSY/darchini3.jpg",
  },
  {
    id: 10,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 17.5,
    description: "Organic cinnamon bark perfect for brewing spiced teas.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co/xHv3MVM/darchini4.jpg",
  },
  {
    id: 11,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 14.99,
    description: "High-quality cinnamon sticks for baking and cooking.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/YPsGH3T/darchini5.jpg",
  },
  {
    id: 12,
    category: "Cinnamon",
    title: "Cinnamon",
    price: 16.25,
    description: "Premium cinnamon powder for adding flavor to recipes.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/Tb1Q6x7/darchini6.jpg",
  },
  {
    id: 13,
    category: "Dry Fruits",
    title: "Mixed Dry Fruits",
    price: 25.99,
    description: "A healthy mix of dried fruits for snacking and cooking.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/LPk9jfG/dryfood1.jpg",
  },
  {
    id: 14,
    category: "Dry Fruits",
    title: "Mixed Dry Fruits",
    price: 27.5,
    description:
      "A variety of premium dry fruits, great for baking or snacking.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/ckrYX52/dryfood2.png",
  },
  {
    id: 15,
    category: "Dry Fruits",
    title: "Mixed Dry Fruits",
    price: 26.99,
    description:
      "Delicious and healthy mix of dried fruits for snacks and recipes.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/YbcxT0s/dryfood3.png",
  },
  {
    id: 16,
    category: "Dry Fruits",
    title: "Mixed Dry Fruits",
    price: 24.5,
    description: "Nutritious dry fruits mix, perfect for a healthy diet.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/Lk7MNy1/dryfood4.png",
  },
  {
    id: 17,
    category: "Dry Fruits",
    title: "Mixed Dry Fruits",
    price: 28.25,
    description: "A premium blend of dried fruits, perfect for any meal.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co/n0BpMCg/dryfood5.jpg",
  },
  {
    id: 18,
    category: "Honey",
    title: "Pure Honey",
    price: 18.99,
    description: "100% natural honey sourced from organic farms.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co/wLDgfkX/honey1.jpg",
  },
  {
    id: 19,
    category: "Honey",
    title: "Pure Honey",
    price: 19.5,
    description: "Freshly harvested honey, perfect for sweetening your dishes.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/MVRpH5v/honey2.jpg",
  },
  {
    id: 20,
    category: "Honey",
    title: "Pure Honey",
    price: 20.75,
    description: "Organic honey with rich flavor and health benefits.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/n3RMCWd/honey3.jpg",
  },
  {
    id: 21,
    category: "Honey",
    title: "Pure Honey",
    price: 21.99,
    description: "Raw honey from sustainable farms, full of nutrients.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co/6sYsqPg/honey4.jpg",
  },
  {
    id: 22,
    category: "Honey",
    title: "Pure Honey",
    price: 17.5,
    description: "Delicious honey with a floral aroma and taste.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/gzNv6My/honey5.jpg",
  },
  {
    id: 23,
    category: "Nuts",
    title: "Mixed Nuts",
    price: 29.99,
    description: "Premium quality mixed nuts, great for snacking and cooking.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co.com/SRDBtzF/nut5.png",
  },
  {
    id: 24,
    category: "Nuts",
    title: "Mixed Nuts",
    price: 30.5,
    description: "A variety of roasted and salted nuts for a healthy snack.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co.com/hCv85TL/nut4.jpg",
  },
  {
    id: 25,
    category: "Nuts",
    title: "Mixed Nuts",
    price: 28.99,
    description:
      "Nutritious and flavorful mixed nuts, perfect for any occasion.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co.com/NpST0g1/nut3.jpg",
  },
  {
    id: 26,
    category: "Nuts",
    title: "Mixed Nuts",
    price: 31.25,
    description: "A balanced mix of almonds, cashews, and other nuts.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co.com/xKkHHkd/nut2.jpg",
  },
  {
    id: 27,
    category: "Nuts",
    title: "Mixed Nuts",
    price: 27.75,
    description: "A healthy blend of nuts perfect for snacking or meals.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co.com/kXjGmHv/nut.jpg",
  },
  {
    id: 28,
    category: "Oil",
    title: "Olive Oil",
    price: 12.99,
    description: "Pure extra virgin olive oil, perfect for cooking.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/vvGLsyC/oil.jpg",
  },
  {
    id: 29,
    category: "Oil",
    title: "Coconut Oil",
    price: 11.99,
    description: "Organic cold-pressed coconut oil for all purposes.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/47hLyB2/oil2.jpg",
  },
  {
    id: 30,
    category: "Oil",
    title: "Sunflower Oil",
    price: 10.99,
    description: "Healthy and light sunflower oil, ideal for frying.",
    rating: 4.5,
    imageUrl: "https://i.ibb.co/h7H6gTQ/oil3.jpg",
  },
  {
    id: 31,
    category: "Oil",
    title: "Mustard Oil",
    price: 9.99,
    description: "Organic mustard oil for cooking and massage.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/Sxtg4gg/oil4.jpg",
  },
  {
    id: 32,
    category: "Oil",
    title: "Sesame Oil",
    price: 13.5,
    description: "Rich in antioxidants, ideal for Asian cuisine.",
    rating: 4.9,
    imageUrl: "https://i.ibb.co/Jp7wXH7/oil5.jpg",
  },
  {
    id: 34,
    category: "Oil",
    title: "Almond Oil",
    price: 14.99,
    description: "Cold-pressed almond oil, great for skin and hair.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/n16Bh8m/oil6.png",
  },
  {
    id: 35,
    category: "Seeds",
    title: "Chia Seeds",
    price: 6.99,
    description: "Rich in fiber and omega-3, perfect for smoothies.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/zJkWhzX/seeds1.jpg",
  },
  {
    id: 36,
    category: "Seeds",
    title: "Flax Seeds",
    price: 5.99,
    description: "Ground flax seeds, a great source of fiber and omega-3.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/2YqMDJ3/seeds3.jpg",
  },
  {
    id: 37,
    category: "Seeds",
    title: "Pumpkin Seeds",
    price: 7.49,
    description: "Roasted pumpkin seeds, a healthy snack high in protein.",
    rating: 4.7,
    imageUrl: "https://i.ibb.co/C2R8nnN/seeds4.jpg",
  },
  {
    id: 38,
    category: "Seeds",
    title: "Sunflower Seeds",
    price: 4.99,
    description: "Perfectly roasted sunflower seeds, great for snacking.",
    rating: 4.5,
    imageUrl: "https://i.ibb.co/GV7d5Hm/seeds5.jpg",
  },
  {
    id: 49,
    category: "Seeds",
    title: "Sesame Seeds",
    price: 3.99,
    description: "Rich in minerals, ideal for baking and cooking.",
    rating: 4.6,
    imageUrl: "https://i.ibb.co/YbkkhRH/seeds6.png",
  },
  {
    id: 40,
    category: "Seeds",
    title: "Watermelon Seeds",
    price: 8.99,
    description: "Crunchy and nutritious watermelon seeds, great for snacking.",
    rating: 4.8,
    imageUrl: "https://i.ibb.co/MBdzK7c/seeds-w2.jpg",
  },
];
